PROG = CShLib

CDEBUG = -g

CPP_SRC = \
CShLibMgr.cpp \
CShLib.cpp \
CShLibSun.cpp

EXTRA_CFLAGS = \
-DOS_UNIX \
-DOS_LINUX \
-I$(INC_DIR)/CFile \
-I$(INC_DIR)/CFileType \
-I$(INC_DIR)/CStrUtil \
-I$(INC_DIR)/CEnv \
-I$(INC_DIR)/CRefPtr \

include $(MAKE_DIR)/lib.mk
